-- img2ui D1 Database Schema
-- Run: npx wrangler d1 execute img2ui-db --file=schema.sql

-- Email collection + user tracking
CREATE TABLE IF NOT EXISTS emails (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  first_seen TEXT NOT NULL DEFAULT (datetime('now')),
  last_used TEXT NOT NULL DEFAULT (datetime('now')),
  total_uses INTEGER NOT NULL DEFAULT 1,
  last_ip TEXT DEFAULT ''
);

-- Design token snapshots (linked to user or anonymous)
CREATE TABLE IF NOT EXISTS design_tokens (
  id TEXT PRIMARY KEY,                -- UUID generated by worker
  user_id TEXT,                       -- NULL for anonymous
  email TEXT DEFAULT '',              -- legacy, kept for migration
  image_key TEXT NOT NULL DEFAULT '',
  tokens_json TEXT NOT NULL,
  annotations_json TEXT DEFAULT '[]',
  holistic_json TEXT DEFAULT '{}',
  provider TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Usage / audit log
CREATE TABLE IF NOT EXISTS usage_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  provider TEXT DEFAULT '',
  ip TEXT DEFAULT '',
  image_key TEXT DEFAULT '',
  input_tokens INTEGER DEFAULT 0,
  output_tokens INTEGER DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Users (identity = email, OAuth-based)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,                -- UUID v4
  email TEXT NOT NULL UNIQUE,
  name TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_login_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- OAuth provider links (many-to-one with users)
CREATE TABLE IF NOT EXISTS auth_providers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  provider TEXT NOT NULL,             -- 'google' | 'github'
  provider_sub TEXT NOT NULL,         -- external ID from provider
  raw_json TEXT DEFAULT '{}',         -- original OAuth response (debug)
  linked_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE(provider, provider_sub)
);

-- Credits ledger (append-only)
CREATE TABLE IF NOT EXISTS credits_ledger (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  amount INTEGER NOT NULL,            -- +10, +3, -1, 0
  type TEXT NOT NULL,                 -- welcome, daily_refill, generation, admin_grant, purchase, figma_export
  memo TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Anonymous usage tracking
CREATE TABLE IF NOT EXISTS anon_usage (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ip TEXT NOT NULL,
  used_at TEXT NOT NULL DEFAULT (datetime('now')),
  claimed_by TEXT,                    -- user_id after claim, NULL if unclaimed
  design_id TEXT,                     -- links to design_tokens.id
  FOREIGN KEY (claimed_by) REFERENCES users(id)
);

-- Indexes (legacy)
CREATE INDEX IF NOT EXISTS idx_emails_email ON emails(email);
CREATE INDEX IF NOT EXISTS idx_tokens_email ON design_tokens(email);
CREATE INDEX IF NOT EXISTS idx_tokens_created ON design_tokens(created_at);
CREATE INDEX IF NOT EXISTS idx_usage_email ON usage_log(email);
CREATE INDEX IF NOT EXISTS idx_usage_created ON usage_log(created_at);

-- Indexes (auth + credits)
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_auth_provider ON auth_providers(provider, provider_sub);
CREATE INDEX IF NOT EXISTS idx_auth_user ON auth_providers(user_id);
CREATE INDEX IF NOT EXISTS idx_credits_user ON credits_ledger(user_id);
CREATE INDEX IF NOT EXISTS idx_credits_type_date ON credits_ledger(user_id, type, created_at);
CREATE INDEX IF NOT EXISTS idx_anon_ip ON anon_usage(ip);
CREATE INDEX IF NOT EXISTS idx_tokens_user ON design_tokens(user_id);
